version: "3"

networks:
  web:
    external: true
  internal:
    external: false

services:
  web:
    build: .
    labels:
      - traefik.backend=web
      - traefik.docker.network=web
      - traefik.port=80
    networks:
      - internal
      - web
    depends_on:
      - mongodb
  mongodb:
    image: mongodb
    networks:
      - internal
    labels:
      - traefik.enable=false
