version: 2
jobs:
  build:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Docker build
          command: docker build -t ${CIRCLE_PROJECT_REPONAME} .
  deploy:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Test
          command: ./ci-deploy.sh
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      # - test:
      #     requires:
      #       - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
